#! /bin/sh

# start keybind daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# general
setxkbmap de

# workspaces
bspc monitor eDP-1 -d 1 2 3 4 5 6

/bin/bash ~/.screenlayout/defalt.sh
echo "default" > ~/.screenlayout/current

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc click_to_focus true

# colors
bspc config normal_border_color     "#3B4252"
bspc config focused_border_color    "#81A1C1"

#window rules
bspc rule -a firefox desktop='^1'
bspc rule -a zoom desktop='^2'
bspc rule -a slack desktop='^5'

# fix some windows
wmname LG3D

# autostart programs
dunst &
gpclient &
flameshot &
nm-applet &
blueman-applet &
firefox &
slack &

# ricing
nitrogen --restore &
picom &
/bin/bash ~/.config/polybar/launch.sh

